name: Sphinx Docs CICD

on:
  push:
    branches:
      - main # 推送到 main 分支触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 把 permissions 提到 job 层级，作用于整个任务
    permissions:
      pages: write # 允许修改 GitHub Pages 相关权限
      id-token: write # 用于增强权限（如 OIDC 相关，v4 插件配合使用）
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install sphinx
          pip install sphinx furo m2r2 sphinx-tables
          # 若有其他依赖（如主题），在此安装
          # pip install sphinx-rtd-theme

      - name: Build Sphinx docs
        run: make html # 生成 _build/html

      - name: Deploy to GitHub Pages
        # 升级到 v4，支持权限配置（结合 job 层级 permissions 生效）
        uses: peaceiris/actions-gh-pages@v4
        with:
          # 改用个人令牌（需在仓库 Secrets 中配置 PERSONAL_ACCESS_TOKEN）
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./build/html
